export const TOGGLE_GAME_CONTROL = 'TOGGLE_GAME_CONTROL';
export const GENERATE_RANDOM_WORD = 'GENERATE_RANDOM_WORD';
export const GUESS_INCORRECT = 'GUESS_INCORRECT';
export const GUESS_CORRECT = 'GUESS_CORRECT';